# Generated by Django 5.2.3 on 2025-06-28 06:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('sur_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('advance_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_contact_number', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10)),
                ('total_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Add Member',
                'verbose_name_plural': 'Add Members',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('floor', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('rent', models.PositiveIntegerField()),
                ('has_attached_washroom', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BalancePaymentProxy',
            fields=[
            ],
            options={
                'verbose_name': '📌 Balance Payments',
                'verbose_name_plural': '📌 Balance Payments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hostel.payment',),
        ),
        migrations.CreateModel(
            name='NewPaymentProxy',
            fields=[
            ],
            options={
                'verbose_name': '➕ New Payment',
                'verbose_name_plural': '➕ New Payment',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hostel.payment',),
        ),
        migrations.AddField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.register'),
        ),
        migrations.AddField(
            model_name='register',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.room'),
        ),
        migrations.CreateModel(
            name='ChangeRoomProxy',
            fields=[
            ],
            options={
                'verbose_name': '🔁 Change Room',
                'verbose_name_plural': '🔁 Change Room',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hostel.room',),
        ),
        migrations.CreateModel(
            name='SwapRoomProxy',
            fields=[
            ],
            options={
                'verbose_name': '🔄 Swap Room',
                'verbose_name_plural': '🔄 Swap Room',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hostel.room',),
        ),
    ]
