# Generated by Django 5.2.3 on 2025-07-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacateMemberProxy',
            fields=[
            ],
            options={
                'verbose_name': '🚪 Vacate Member',
                'verbose_name_plural': '🚪 Vacate Members',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hostel.register',),
        ),
        migrations.AddField(
            model_name='register',
            name='job_or_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
