# Generated by Django 5.2.3 on 2025-06-25 04:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
