# Generated by Django 5.2.3 on 2025-06-25 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_alter_member_joined_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Register',
        ),
    ]
