# Generated by Django 5.2.3 on 2025-06-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_rename_member_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'Add Member', 'verbose_name_plural': 'Add Member'},
        ),
    ]
