# Generated by Django 5.2.3 on 2025-06-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_alter_register_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'Add Member', 'verbose_name_plural': 'Add Members'},
        ),
        migrations.RemoveField(
            model_name='register',
            name='age',
        ),
        migrations.AlterField(
            model_name='register',
            name='joined_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='rent',
            field=models.PositiveIntegerField(),
        ),
    ]
