# Generated by Django 5.2.3 on 2025-06-26 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_alter_register_options_remove_register_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRoomProxy',
            fields=[
            ],
            options={
                'verbose_name': '🔁 Change Room',
                'verbose_name_plural': '🔁 Change Room',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hostel.room',),
        ),
        migrations.CreateModel(
            name='SwapRoomProxy',
            fields=[
            ],
            options={
                'verbose_name': '🔄 Swap Room',
                'verbose_name_plural': '🔄 Swap Room',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hostel.room',),
        ),
    ]
