# Generated by Django 5.2.3 on 2025-06-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_changeroomproxy_swaproomproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
